- hosts: ubuntu
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes

- hosts:  ubuntu
  tasks: 
  - name: install  Apache ,tree and git packages
    apt:
      name: 
        - apache2
        - tree 
        - git 
      state: latest 
      
  - name: Start Apache service and enabled 
    service: 
      name: apache2
      state: started 
      enabled: yes 

  - name: Copy files HW1 to remote host 
    copy:
      src: "./"
      dest: /root/